feat: check file .env

diff --git a/.github/workflows/action.yml b/.github/workflows/action.yml
--- a/.github/workflows/action.yml
+++ b/.github/workflows/action.yml
@@ -14,6 +14,13 @@ jobs:
       - name: Checkout repository
         uses: actions/checkout@v4
 
+      - name: Check if .env file is committed
+        run: |
+          if [ -f .env ] || [ -f web/.env ]; then
+            echo "ERROR: .env file should not be committed to the repository!"
+            exit 1
+          fi
+
       - name: Setup Node.js for Backend
         uses: actions/setup-node@v4
         with:
